### ISSUE TITLE
Create a VU meter

### ISSUE THREAD

**Issue by francoismartin** [pimoroni/blinkt#33]
Hi,

Do you have idea, how can I create a vu meter with blinkit with the input and output sound ?
Like that : https://vimeo.com/114906251 (for output sound)

Or Can I adapt your [code of scroll phat](https://learn.pimoroni.com/tutorial/sandyj/scroll-phat-spectrum-analyser) for blinkit

Thanks

**Comment by Gadgetoid** [comment]
It's probably not as helpful as it could be, but for Speaker pHAT we've done this using an ALSA plugin: https://github.com/pimoroni/speaker-phat/tree/master/alsa-plugin

I will be adding APA102 support into this code at some point, which may include Blinkt support simply because that would be cool :D

**Comment by Gadgetoid** [comment]
This has now been moved to its own project, Pi VU Meter, which includes Blinkt support specifically: https://github.com/pimoroni/pivumeter

It's a little embryonic at the moment, but we'll be building a nice easy to use package eventually.
